### ISSUE TITLE
常见问题

### ISSUE THREAD

**Issue by UCloudDocs** [UCloudDoc-Team/ufile#160]
# 常见问题

查看产品文档请点击下方链接

[https://docs.ucloud.cn/ufile/tools/us3Browser/questions](https://docs.ucloud.cn/ufile/tools/us3Browser/questions)

**Comment by key911** [comment]
文件夹里子文件过多，会报错。
错误码：XMLParseError
详细信息：error on line 6 at colunm8:opening and ending tag mismatch
