### ISSUE TITLE
静态网站托管

### ISSUE THREAD

**Issue by UCloudDocs** [UCloudDoc-Team/ufile#53]
# 静态网站托管

查看产品文档请点击下方链接

[https://docs.ucloud.cn/ufile/guide/static_websit_hosring](https://docs.ucloud.cn/ufile/guide/static_websit_hosring)

**Comment by SAMZONG** [comment]
已开通了子目录首页功能，但并没有实现 自动返回 `index.html` 的内容；需要手工输入 index.html 才能访问到页面。
