### ISSUE TITLE
常用命令

### ISSUE THREAD

**Issue by UCloudDocs** [UCloudDoc-Team/ufile#95]
# 常用命令

查看产品文档请点击下方链接

[https://docs.ucloud.cn/ufile/tools/us3cli/command](https://docs.ucloud.cn/ufile/tools/us3cli/command)

**Comment by pymongo** [comment]
us3cli cp 的时候怎样隐藏进度条？

例如 curl 命令可以加上 -s 参数隐藏进度条 `-s tells cURL not to show a progress meter`
